debugging pipeline 3 trying out RSA only checklist service

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -65,45 +65,45 @@ jobs:
 
         EOF
 
-    - name: Connect to Keycloak Instance & start Keycloak + DB
-      run: |
-        eval "$(ssh-agent -s)"
-        echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
-        chmod 600 private_key.pem
-        ssh-add private_key.pem
-        ssh -v -o StrictHostKeyChecking=no -o PubkeyAcceptedKeyTypes=+ssh-rsa -o HostKeyAlgorithms=+ssh-rsa -i private_key.pem ubuntu@184.72.205.213
+    # - name: Connect to Keycloak Instance & start Keycloak + DB
+    #   run: |
+    #     eval "$(ssh-agent -s)"
+    #     echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
+    #     chmod 600 private_key.pem
+    #     ssh-add private_key.pem
+    #     ssh -v -o StrictHostKeyChecking=no -o PubkeyAcceptedKeyTypes=+ssh-rsa -o HostKeyAlgorithms=+ssh-rsa -i private_key.pem ubuntu@184.72.205.213
          
-          # Ensure repository is initialized correctly
-          if [ ! -d ".git" ]; then 
-            git init .
-            git remote add origin ${{ secrets.DEPLOY_REPO_URL }}
-          fi
+    #       # Ensure repository is initialized correctly
+    #       if [ ! -d ".git" ]; then 
+    #         git init .
+    #         git remote add origin ${{ secrets.DEPLOY_REPO_URL }}
+    #       fi
         
-          # stop the keycloak and remove it
-          sudo docker stop keycloak && sudo docker rm keycloak
+    #       # stop the keycloak and remove it
+    #       sudo docker stop keycloak && sudo docker rm keycloak
 
-          # start the keycloak and db service
-          sudo docker compose -f compose1.yaml up -d
+    #       # start the keycloak and db service
+    #       sudo docker compose -f compose1.yaml up -d
 
-          # see if the keycloak and keycloak DB are running
-          sudo docker ps
-        EOF
-    # - name: Make checklist service 
-    #   run: | 
-    #     ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@44.203.90.240 << 'EOF'
-          
-    #       # Pull latest changes
-    #       git pull origin main
-
-    #       # Deploy Checklist Service
-    #       cd backend/checklist-service
-
-    #       docker stop checklist-service || true
-    #       docker rm checklist-service || true
-
-    #       # Build and start checklist-service (only if not already running)
-    #       docker build -t checklist-service .
-    #       docker run -d -p 5002:5002 --env-file /home/ubuntu/app/backend/checklist-service/.env --name checklist-service checklist-service || echo "Checklist service container already running or failed to start"
-
+    #       # see if the keycloak and keycloak DB are running
+    #       sudo docker ps
     #     EOF
+    - name: Make checklist service 
+      run: | 
+        ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@44.203.90.240 << 'EOF'
+          
+          # Pull latest changes
+          git pull origin main
+
+          # Deploy Checklist Service
+          cd backend/checklist-service
+
+          docker stop checklist-service || true
+          docker rm checklist-service || true
+
+          # Build and start checklist-service (only if not already running)
+          docker build -t checklist-service .
+          docker run -d -p 5002:5002 --env-file /home/ubuntu/app/backend/checklist-service/.env --name checklist-service checklist-service || echo "Checklist service container already running or failed to start"
+
+        EOF
         
